### ISSUE TITLE
setup uc-cdis/pythonbase Docker image

### ISSUE THREAD

**Issue by frickjack** [uc-cdis/cloud-automation#168] opened 2018-02-16 16:05 UTC
Note: requires #170 

Currently sheepdog and peregrine replicate a lot of setup in Dockerfile, and fence runs Apache instead of nginx, so when we want to do some standard change (ex - logging, SSL, change base OS, change python version) - we need to change all 3 repos.  I'd like to setup a 'pythonbase' repo that just has a Dockerfile that sets up a standard python+nginx environment that our different service Dockerfile's inherit from, and just add a new uwsgi.ini - ex:

```
from quay.io/uc-cdis/pythonbase:python2.7_1.0

COPY . /peregrine
COPY ./deployment/uwsgi/uwsgi.ini /etc/uwsgi/uwsgi.ini

RUN pip install -r requirements.txt \
    && COMMIT=`git rev-parse HEAD` && echo "COMMIT=\"${COMMIT}\"" >peregrine/version_data.py \
    && VERSION=`git describe --always --tags` && echo "VERSION=\"${VERSION}\"" >>peregrine/version_data.py \
    && cd /peregrine/src/gdcdictionary && DICTCOMMIT=`git rev-parse HEAD` && echo "DICTCOMMIT=\"${DICTCOMMIT}\"" >>/peregrine/peregrine/version_data.py \
    && DICTVERSION=`git describe --always --tags` && echo "DICTVERSION=\"${DICTVERSION}\"" >>/peregrine/peregrine/version_data.py \
    && python setup.py install

WORKDIR /var/www/peregrine
```

**Comment by philloooo** [comment] 2018-05-10 21:35
duplicate of https://github.com/uc-cdis/cloud-automation/issues/296

**Closed by philloooo** 2018-05-10 21:35 UTC
